### ISSUE TITLE
Filter most trending products by category

### ISSUE THREAD

**Issue by JohnPetros** [CtrI-Alt-Del/stocker#104]
- Add `categoryId` to the flow get the most trending products: `controller`, `use case` and `repository`.
- If `categoryId` is undefined all products of all categories should be returned.
- if `categoryId` belongs a parent category, all products whose category is a subcategory of this parent category should be returned as well.

**Comment by 0thigs** [comment]
Testa @FaelSantoss kkkkkkkkkkkkk
