### ISSUE TITLE
Categories filtering on backend

### ISSUE THREAD

**Issue by JohnPetros** [CtrI-Alt-Del/stocker#241]
Filter categories by name.
I have already added the `name` prop to `CategoriesListParams`
```
export type CategoriesListParams = {
  name?: string
  page: number
  companyId: string
}

```
Alter controller, use case and repository if it will be needed.
Do not forget that front end will filter by using query params.
Do not forget to do manual tests.

**Comment by kaufon** [comment]
Items cout is wrong,returning full item count instead of only filtered items

**Comment by 0thigs** [comment]
banana

**Comment by kaufon** [comment]
It should return all names that contain that string example:
if name === dd ,then itshould return dd, ddd, dddd, dddd not only dd
currently only returning categories with exact name on query params
