### ISSUE TITLE
Locations filtering on backend

### ISSUE THREAD

**Issue by JohnPetros** [CtrI-Alt-Del/stocker#242]
Filter locations by name.
I have already added the `name` prop to `CategoriesListParams`
```
export type CategoriesListParams = {
  name?: string
  page: number
  companyId: string
}

```
Change controller, use case and repository if necessary.
Do not forget that front end will filter by using query params.
Do not forget to do manual tests.

**Comment by kaufon** [comment]
fucking closed the issue,did nothing in the prisma repository,was wrong and in the use case tried to map some shit that didnt exist,done and closed
