### ISSUE TITLE
Inventory movements filtering

### ISSUE THREAD

**Issue by JohnPetros** [CtrI-Alt-Del/stocker#245]
Filter inventory movements by movement type (`inbound` or `outbound`),  range of dates (`startDate` and `endDate`)
product (`productId`) and employee (`employeeId`).

```
import type { InventoryMovementType } from './inventory-movement-type'

export type InventoryMovementsListParams = {
  page?: number
  companyId?: string
  startDate?: Date
  endDate?: Date
  employeeId?: string
  movementType?: InventoryMovementType
  productId?: string
}
```
Change controller, use case and repository if necessary.
Do not forget that front end will filter by using query params.
Do not forget to do manual tests.

**Comment by kaufon** [comment]
count is wrong,returning full count instead of only filtered item.

The return is also kind fucked up return product with entity instead of dto,try looking into that
