### ISSUE TITLE
List inventory movements

### ISSUE THREAD

**Issue by JohnPetros** [CtrI-Alt-Del/stocker#46]
Use Case: 
- `name`: ListInventoryMovementsUseCase
- `dependencies`: inventoryMovementsRepository
- `request`: `{ page: number }`
- `response`: `InventoryMovements[]`

obs: Implements `findMany` of InventoryMovementsRepository

Controller: 
- `name`: ListInventoryMovementsController
- `http query params`: `{ page: number }`
- `http send`: `InventoryMovement[], 200`

Route:
- `method`: `get`
- `endpoint`: `/inventory-movements`

**Comment by 0thigs** [comment]
done
