### ISSUE TITLE
Not found page

### ISSUE THREAD

**Issue by JohnPetros** [CtrI-Alt-Del/stocker#55]
Create not found page component inspired by this [design](https://dribbble.com/shots/18497774-No-results-found) :

**Comment by kaufon** [comment]
![images (16).jpeg](https://github.com/user-attachments/assets/cefeceef-08a2-45ad-9772-4d96ca0683d0)

Thinking of using an image like this,what you think

**Comment by 0thigs** [comment]
2 nego numa task dessa é d cair o cu da bunda

**Comment by kaufon** [comment]
Prezado @0thigs , gostaria de lembrar que este ambiente não é apropriado para desrespeitos ou expressões vulgares. Peço gentilmente que mantenhamos um padrão de comunicação mais elevado e respeitoso.

**Comment by 0thigs** [comment]
vai da o cukkkkkk

**Comment by kaufon** [comment]
E o bananinha
