### ISSUE TITLE
Inventory summary use case

### ISSUE THREAD

**Issue by JohnPetros** [CtrI-Alt-Del/stocker#79]
Use Case: 
- `name`: ReportInventorySummaryUseCase
- `dependencies`: batchesRepository, inventoryMovementsRepository
- `response`: `{ batchesCount: number, itemsCount: number, inboundInventoryMovementsCount: number,  outboundInventoryMovementsCount }`

Controller: 
- `name`: ReportInventorySummaryController
- `http send`: `{ batchesCount: number, itemsCount: number, inboundInventoryMovementsCount: number,  outboundInventoryMovementsCount }`, 200`

Route:
- `method`: `get`
- `endpoint`: `/reports/inventory-summary`

**Comment by kaufon** [comment]
é o baneinas
