### ISSUE TITLE
Export inventory to csv file use case

### ISSUE THREAD

**Issue by JohnPetros** [CtrI-Alt-Del/stocker#84]
Use Case: 
- `name`: ExportInventoryToCsvFileUseCase
- `dependencies`: productsRepository, csvProvider
- `response`: `CsvFileBuffer`

- Use `csvProvider` to add the columns to the file: `Nome`, `Qtd. de lotes`, `Qtd. de lançamentos de entrada`,  `Qtd. de lançamentos de saída`, `Estoque atual`, `Estoque mínimo` and `Nível de estoque`

Controller: 
- `name`: ExportInventoryToCsvFileController
- `http send`: `CsvFileBuffer`, 200`

Route:
- `method`: `get`
- `endpoint`: `/reports/inventory/csv`

**Comment by 0thigs** [comment]
Its done
